if(NOT GNURADIO_FUNCUBE_FOUND)
  pkg_check_modules (GNURADIO_FUNCUBE_PKG libgnuradio-funcube)
  find_path(GNURADIO_FUNCUBE_INCLUDE_DIRS NAMES funcube/api.h
    PATHS
    ${GNURADIO_FUNCUBE_PKG_INCLUDE_DIRS}
    /usr/include
    /usr/local/include
  )

  find_library(GNURADIO_FUNCUBE_LIBRARIES NAMES gnuradio-funcube
    PATHS
    ${GNURADIO_FUNCUBE_PKG_LIBRARY_DIRS}
    /usr/lib
    /usr/local/lib
  )

if(GNURADIO_FUNCUBE_INCLUDE_DIRS AND GNURADIO_FUNCUBE_LIBRARIES)
  set(GNURADIO_FUNCUBE_FOUND TRUE CACHE INTERNAL "gnuradio-funcube found")
  message(STATUS "Found gnuradio-funcube: ${GNURADIO_FUNCUBE_INCLUDE_DIRS}, ${GNURADIO_FUNCUBE_LIBRARIES}")
else(GNURADIO_FUNCUBE_INCLUDE_DIRS AND GNURADIO_FUNCUBE_LIBRARIES)
  set(GNURADIO_FUNCUBE_FOUND FALSE CACHE INTERNAL "gnuradio-funcube found")
  message(STATUS "gnuradio-funcube not found.")
endif(GNURADIO_FUNCUBE_INCLUDE_DIRS AND GNURADIO_FUNCUBE_LIBRARIES)

mark_as_advanced(GNURADIO_FUNCUBE_LIBRARIES GNURADIO_FUNCUBE_INCLUDE_DIRS)

endif(NOT GNURADIO_FUNCUBE_FOUND)
