#ifndef AIRSPY_WRAPPER_H
#define AIRSPY_WRAPPER_H

// Remap ALL conflicting symbols for AIRSPY
#define RECEIVER_MODE_OFF    AIRSPY_RECEIVER_MODE_OFF
#define RECEIVER_MODE_RX     AIRSPY_RECEIVER_MODE_RX
#define receiver_mode_t      airspy_receiver_mode_t

#define GPIO_PORT0  AIRSPY_GPIO_PORT0
#define GPIO_PORT1  AIRSPY_GPIO_PORT1
#define GPIO_PORT2  AIRSPY_GPIO_PORT2
#define GPIO_PORT3  AIRSPY_GPIO_PORT3
#define GPIO_PORT4  AIRSPY_GPIO_PORT4
#define GPIO_PORT5  AIRSPY_GPIO_PORT5
#define GPIO_PORT6  AIRSPY_GPIO_PORT6
#define GPIO_PORT7  AIRSPY_GPIO_PORT7

#define GPIO_PIN0  AIRSPY_GPIO_PIN0
#define GPIO_PIN1  AIRSPY_GPIO_PIN1
#define GPIO_PIN2  AIRSPY_GPIO_PIN2
#define GPIO_PIN3  AIRSPY_GPIO_PIN3
#define GPIO_PIN4  AIRSPY_GPIO_PIN4
#define GPIO_PIN5  AIRSPY_GPIO_PIN5
#define GPIO_PIN6  AIRSPY_GPIO_PIN6
#define GPIO_PIN7  AIRSPY_GPIO_PIN7
#define GPIO_PIN8  AIRSPY_GPIO_PIN8
#define GPIO_PIN9  AIRSPY_GPIO_PIN9
#define GPIO_PIN10 AIRSPY_GPIO_PIN10
#define GPIO_PIN11 AIRSPY_GPIO_PIN11
#define GPIO_PIN12 AIRSPY_GPIO_PIN12
#define GPIO_PIN13 AIRSPY_GPIO_PIN13
#define GPIO_PIN14 AIRSPY_GPIO_PIN14
#define GPIO_PIN15 AIRSPY_GPIO_PIN15
#define GPIO_PIN16 AIRSPY_GPIO_PIN16
#define GPIO_PIN17 AIRSPY_GPIO_PIN17
#define GPIO_PIN18 AIRSPY_GPIO_PIN18
#define GPIO_PIN19 AIRSPY_GPIO_PIN19
#define GPIO_PIN20 AIRSPY_GPIO_PIN20
#define GPIO_PIN21 AIRSPY_GPIO_PIN21
#define GPIO_PIN22 AIRSPY_GPIO_PIN22
#define GPIO_PIN23 AIRSPY_GPIO_PIN23
#define GPIO_PIN24 AIRSPY_GPIO_PIN24
#define GPIO_PIN25 AIRSPY_GPIO_PIN25
#define GPIO_PIN26 AIRSPY_GPIO_PIN26
#define GPIO_PIN27 AIRSPY_GPIO_PIN27
#define GPIO_PIN28 AIRSPY_GPIO_PIN28
#define GPIO_PIN29 AIRSPY_GPIO_PIN29
#define GPIO_PIN30 AIRSPY_GPIO_PIN30
#define GPIO_PIN31 AIRSPY_GPIO_PIN31

extern "C" {
#include <libairspy/airspy.h>
}

// Undefine ALL remapped symbols
#undef RECEIVER_MODE_OFF
#undef RECEIVER_MODE_RX
#undef receiver_mode_t

#undef GPIO_PORT0
#undef GPIO_PORT1
#undef GPIO_PORT2
#undef GPIO_PORT3
#undef GPIO_PORT4
#undef GPIO_PORT5
#undef GPIO_PORT6
#undef GPIO_PORT7

#undef GPIO_PIN0
#undef GPIO_PIN1
#undef GPIO_PIN2
#undef GPIO_PIN3
#undef GPIO_PIN4
#undef GPIO_PIN5
#undef GPIO_PIN6
#undef GPIO_PIN7
#undef GPIO_PIN8
#undef GPIO_PIN9
#undef GPIO_PIN10
#undef GPIO_PIN11
#undef GPIO_PIN12
#undef GPIO_PIN13
#undef GPIO_PIN14
#undef GPIO_PIN15
#undef GPIO_PIN16
#undef GPIO_PIN17
#undef GPIO_PIN18
#undef GPIO_PIN19
#undef GPIO_PIN20
#undef GPIO_PIN21
#undef GPIO_PIN22
#undef GPIO_PIN23
#undef GPIO_PIN24
#undef GPIO_PIN25
#undef GPIO_PIN26
#undef GPIO_PIN27
#undef GPIO_PIN28
#undef GPIO_PIN29
#undef GPIO_PIN30
#undef GPIO_PIN31

#endif // AIRSPY_WRAPPER_H
